name = "i"
main = "index.ts"
compatibility_date = "2025-10-01"
workers_dev = true
account_id = "b19946d3edbafe04ab6c83e3c5084b3a"
compatibility_flags = [ "nodejs_compat" ]

[placement]
mode = "smart"

[[kv_namespaces]]
binding = "ICONS_KV"
id = "7415439862844521bf9d339ee641b2c4"